name: ğŸš€ Deploy to Live Servers

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: ğŸ”„ Deploy to All Servers
    runs-on: self-hosted

    steps:
      - name: â¬‡ï¸ Checkout Source Code
        uses: actions/checkout@v3

      - name: ğŸš€ Deploy on Server 1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd docker-easy || exit 1
            docker system prune -af
            git pull origin main
            docker compose down --remove-orphans
            docker compose up -d --build

      - name: ğŸš€ Deploy on Server 2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST1 }}
          username: ${{ secrets.SSH_USER1 }}
          port: ${{ secrets.SSH_PORT1 }}
          key: ${{ secrets.SSH_KEY1 }}
          script: |
            set -e
            cd docker-easy || exit 1
            docker system prune -af
            git pull origin main
            docker compose down --remove-orphans
            docker compose up -d --build
            
